# Generated by Django 3.1.3 on 2020-11-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_zone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='Serial',
        ),
    ]
